### ISSUE TITLE
Weight Uploads not posting in HP

### ISSUE THREAD

**Issue by secondhelpingsadmin** [megandalster/sh-homeplate#69]
I am certain that I entered weights for Hilton Head's Feb Feb 8 routs on a tablet and unloaded,  I don't remember the weight amounts, but they were substantial.  See HP for HHI for that date, shows a log on time of 9;04 which right.  We have reports of similar fails, but I don't have documentation..... I hear about them after the fact, few details or verification.
Thursday February 8 | 0 | 10 | 5 | 0 | 0 | 0 | 09:04-09:04
-- | -- | -- | -- | -- | -- | -- | --

Today, 2/17, (11:16) I entered weights for a Bluffton route: Miscellaneous pick up, 21 pounds.  Upload looked good, but nothing posted.

**Comment by megandalster** [comment]
The tablet that you used (95d13979f48f5c7f) to upload the 21 pounds for Bluffton today wasn' t registered with HP.  I just now registered it, and the 21 pounds posted.

Same for the Feb 8 Hilton Head weights.  The tablet used there (1158af9cff2a211c) was not registered with Homeplate.  I registered it and the weights are now posted.

I will work next on the tablet registry (Issue #57) so that you can directly check and update the list of registered tablets yourself whenever you're logged into Homeplate.

**Comment by secondhelpingsadmin** [comment]
That's good news (as easily fixable, and the data retained).  Tks.

**Comment by secondhelpingsadmin** [comment]
Appears to be same condition - upload time stamp but no data - for these routes/dates:
HH: 2/6, 2/12, 2/15.
Bluffton 2/4, 2/11.

**Comment by secondhelpingsadmin** [comment]
Can you make the tablet table and verification just the last 4 characters of the tablet ID?  It's a long, complicated string.  That should provide adequate security.

**Comment by megandalster** [comment]
Good idea!

**Comment by megandalster** [comment]
I checked the 5 routes and dates above, and there is no more data on the server for these.  The data shows no more tablets that are unregistered with Homeplate, so this problem is different from the one I fixed earlier.  

FYI, here's a list of the tablet ids that the software will accept data from.  (I hope this list now agrees with reality :-) . If you have a tablet in your inventory whose id is not in this list, let me know.

$deviceIds = array("ab92221e6ada959c",
				"486e7427693b6422",
                			"532c5d0e6f5aca9d", // Added 1/9/18
                			"4c05048923e042aa", // Added 2/8/18
                			"cf5c1ab761188ac6", // Added 2/8/18
                			"3e1195faad76f5c4", // Added 2/8/18
                			"95191c10a7c74541", // Added 2/8/18
                			"95d13979f48f5c7f", // Added 2/17/18
                			"1158af9cff2a211c", // Added 2.17/18
				"5e47d9a9796482da",
				"a207427fee8357ab", //Added 11/24/2014
				"49f2420a374c1b0f", //Added 8/18/2015
				"1f5b811fde353d0",  //Added 9/29/2015
				"9dba4527e58b85f3", //Added 9/29/2015
				"4d4365330aa76127", //Added 9/29/2015				
				"b81b930d5ac05962",
				"a22f0b9aa9d28df9", //Added 3/3/2016
				"e029ceac5d51b6b", //Added 3/3/2016
				"d3065bbe7dd5c4ad"
				);

**Comment by secondhelpingsadmin** [comment]
Will attempt to verify all current tablets in use.  Some on list are obsolete/discarded.
